conformant = "Partial"
notes = """
Does not support field specifiers.
Emits "attribute not initialized" error for dataclass field.
"""
output = """
dataclasses_transform_class.py:28:4 Uninitialized attribute [13]: Attribute `not_a_field` is declared in class `ModelBase` to have type `str` but is never initialized.
dataclasses_transform_class.py:48:0 Invalid inheritance [39]: Non-frozen dataclass `Customer1Subclass` cannot inherit from frozen dataclass `Customer1`.
dataclasses_transform_class.py:57:7 Unexpected keyword [28]: Unexpected keyword argument `other_name` to call `Customer1.__init__`.
dataclasses_transform_class.py:60:0 Invalid assignment [41]: Cannot reassign final attribute `c1_1.id`.
dataclasses_transform_class.py:63:7 Too many arguments [19]: Call `Customer1.__init__` expects 0 positional arguments, 2 were provided.
dataclasses_transform_class.py:69:5 Unsupported operand [58]: `<` is not supported for operand types `Customer1` and `Customer1`.
dataclasses_transform_class.py:79:7 Too many arguments [19]: Call `Customer2.__init__` expects 0 positional arguments, 2 were provided.
dataclasses_transform_class.py:87:4 Uninitialized attribute [13]: Attribute `not_a_field` is declared in class `GenericModelBase` to have type `Variable[T]` but is never initialized.
dataclasses_transform_class.py:108:4 Uninitialized attribute [13]: Attribute `not_a_field` is declared in class `ModelBaseFrozen` to have type `str` but is never initialized.
dataclasses_transform_class.py:119:0 Invalid assignment [41]: Cannot reassign final attribute `c3_1.id`.
"""
conformance_automated = "Fail"
errors_diff = """
Line 28: Unexpected errors ['dataclasses_transform_class.py:28:4 Uninitialized attribute [13]: Attribute `not_a_field` is declared in class `ModelBase` to have type `str` but is never initialized.']
Line 57: Unexpected errors ['dataclasses_transform_class.py:57:7 Unexpected keyword [28]: Unexpected keyword argument `other_name` to call `Customer1.__init__`.']
Line 87: Unexpected errors ['dataclasses_transform_class.py:87:4 Uninitialized attribute [13]: Attribute `not_a_field` is declared in class `GenericModelBase` to have type `Variable[T]` but is never initialized.']
Line 108: Unexpected errors ['dataclasses_transform_class.py:108:4 Uninitialized attribute [13]: Attribute `not_a_field` is declared in class `ModelBaseFrozen` to have type `str` but is never initialized.']
"""
