conformant = "Partial"
notes = """
Incorrectly evaluates type of specialized type alias parameterized with ParamSpec.
Allows some illegal annotation forms to be interpreted as valid type aliases.
"""
output = """
aliases_traditional.py:68:17 - error: "assert_type" mismatch: expected "(int, str, str) -> None" but received "(int, str, str) -> None" (reportGeneralTypeIssues)
aliases_traditional.py:76:24 - error: Expected no type arguments for class "int" (reportGeneralTypeIssues)
aliases_traditional.py:76:24 - error: Expected no type arguments for class "NoneType" (reportGeneralTypeIssues)
aliases_traditional.py:77:9 - error: Type "list[int | None]" is already specialized (reportGeneralTypeIssues)
aliases_traditional.py:78:29 - error: Too many type arguments provided for "GoodTypeAlias4[T@GoodTypeAlias4]"; expected 1 but received 2
aliases_traditional.py:79:29 - error: Too many type arguments provided for "GoodTypeAlias8[T@GoodTypeAlias8]"; expected 1 but received 2
aliases_traditional.py:80:24 - error: Expected ParamSpec, ellipsis, or list of types
aliases_traditional.py:81:9 - error: Could not specialize type "GoodTypeAlias12[TFloat@GoodTypeAlias12]"
  Type "str" cannot be assigned to type "float"
    "str" is incompatible with "float"
aliases_traditional.py:106:9 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:107:9 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:108:9 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:109:9 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:110:9 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:113:9 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:114:9 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:115:10 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:116:10 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:118:10 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:119:10 - error: Variable not allowed in type expression (reportGeneralTypeIssues)
aliases_traditional.py:133:6 - error: Object of type "type[list[Unknown]] | type[set[Unknown]]" is not callable (reportGeneralTypeIssues)
aliases_traditional.py:135:5 - error: Type "list[Unknown]" is already specialized (reportGeneralTypeIssues)
aliases_traditional.py:135:5 - error: Type "set[Unknown]" is already specialized (reportGeneralTypeIssues)
"""
