conformant = "Partial"
notes = """
Does not generate a union type for __new__ and __init__ when converting class to callable.
Does not ignore __init__ based on __new__ return type when converting class to callable.
Does not support __new__ return type that is different from class being constructed.
Does not use annotated type of self in __init__ method to generate return type of callable.
"""
conformance_automated = "Fail"
errors_diff = """
Line 51: Expected 1 errors
Line 127: Expected 1 errors
Line 144: Expected 1 errors
Line 36: Unexpected errors ['File "constructors_callable.py", line 36, in <module>: Callable[[Any], Class1] [reveal-type]']
Line 49: Unexpected errors ['File "constructors_callable.py", line 49, in <module>: Callable[[Any], Class2] [reveal-type]']
Line 50: Unexpected errors ['File "constructors_callable.py", line 50, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]', 'File "constructors_callable.py", line 50, in <module>: Any [assert-type]']
Line 57: Unexpected errors ['File "constructors_callable.py", line 57, in __new__: bad return type [bad-return-type]']
Line 63: Unexpected errors ['File "constructors_callable.py", line 63, in <module>: Callable[[Any], Class3] [reveal-type]']
Line 73: Unexpected errors ['File "constructors_callable.py", line 73, in __new__: bad return type [bad-return-type]']
Line 77: Unexpected errors ['File "constructors_callable.py", line 77, in <module>: Callable[[Any], Class4] [reveal-type]']
Line 78: Unexpected errors ['File "constructors_callable.py", line 78, in <module>: nothing [assert-type]']
Line 97: Unexpected errors ['File "constructors_callable.py", line 97, in <module>: Callable[[Any], Class5] [reveal-type]']
Line 100: Unexpected errors ['File "constructors_callable.py", line 100, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]', 'File "constructors_callable.py", line 100, in <module>: Any [assert-type]']
Line 105: Unexpected errors ['File "constructors_callable.py", line 105, in <module>: Invalid keyword argument x to function <callable> [wrong-keyword-args]', 'File "constructors_callable.py", line 105, in <module>: Any [assert-type]']
Line 117: Unexpected errors ['File "constructors_callable.py", line 117, in __new__: bad return type [bad-return-type]']
Line 125: Unexpected errors ['File "constructors_callable.py", line 125, in <module>: Callable[[Any], Class6] [reveal-type]']
Line 126: Unexpected errors ['File "constructors_callable.py", line 126, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]', 'File "constructors_callable.py", line 126, in <module>: Any [assert-type]']
Line 142: Unexpected errors ['File "constructors_callable.py", line 142, in <module>: Callable[[Any], Class6Any] [reveal-type]']
Line 143: Unexpected errors ['File "constructors_callable.py", line 143, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]']
Line 161: Unexpected errors ['File "constructors_callable.py", line 161, in <module>: Callable[[Any], Class7] [reveal-type]']
Line 164: Unexpected errors ['File "constructors_callable.py", line 164, in <module>: Class7 [assert-type]']
Line 165: Unexpected errors ['File "constructors_callable.py", line 165, in <module>: Class7 [assert-type]']
Line 182: Unexpected errors ['File "constructors_callable.py", line 182, in <module>: Callable[[Any], Class8[nothing]] [reveal-type]']
Line 183: Unexpected errors ['File "constructors_callable.py", line 183, in <module>: Function <callable> expects 1 arg(s), got 2 [wrong-arg-count]', 'File "constructors_callable.py", line 183, in <module>: Any [assert-type]']
Line 193: Unexpected errors ['File "constructors_callable.py", line 193, in <module>: Callable[[Any], Class9] [reveal-type]']
Line 194: Unexpected errors ['File "constructors_callable.py", line 194, in <module>: Function <callable> expects 1 arg(s), got 2 [wrong-arg-count]', 'File "constructors_callable.py", line 194, in <module>: Any [assert-type]']
"""
output = """
File "constructors_callable.py", line 36, in <module>: Callable[[Any], Class1] [reveal-type]
File "constructors_callable.py", line 38, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]
File "constructors_callable.py", line 39, in <module>: Invalid keyword argument y to function <callable> [wrong-keyword-args]
File "constructors_callable.py", line 49, in <module>: Callable[[Any], Class2] [reveal-type]
File "constructors_callable.py", line 50, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]
File "constructors_callable.py", line 50, in <module>: Any [assert-type]
File "constructors_callable.py", line 57, in __new__: bad return type [bad-return-type]
Called from (traceback):
  line 64, in current file
File "constructors_callable.py", line 63, in <module>: Callable[[Any], Class3] [reveal-type]
File "constructors_callable.py", line 65, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]
File "constructors_callable.py", line 66, in <module>: Invalid keyword argument y to function <callable> [wrong-keyword-args]
File "constructors_callable.py", line 67, in <module>: Function <callable> expects 1 arg(s), got 2 [wrong-arg-count]
File "constructors_callable.py", line 73, in __new__: bad return type [bad-return-type]
Called from (traceback):
  line 78, in current file
File "constructors_callable.py", line 77, in <module>: Callable[[Any], Class4] [reveal-type]
File "constructors_callable.py", line 78, in <module>: nothing [assert-type]
File "constructors_callable.py", line 79, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]
File "constructors_callable.py", line 80, in <module>: Invalid keyword argument y to function <callable> [wrong-keyword-args]
File "constructors_callable.py", line 97, in <module>: Callable[[Any], Class5] [reveal-type]
File "constructors_callable.py", line 100, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]
File "constructors_callable.py", line 100, in <module>: Any [assert-type]
File "constructors_callable.py", line 105, in <module>: Invalid keyword argument x to function <callable> [wrong-keyword-args]
File "constructors_callable.py", line 105, in <module>: Any [assert-type]
File "constructors_callable.py", line 117, in __new__: bad return type [bad-return-type]
Called from (traceback):
  line 127, in current file
File "constructors_callable.py", line 125, in <module>: Callable[[Any], Class6] [reveal-type]
File "constructors_callable.py", line 126, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]
File "constructors_callable.py", line 126, in <module>: Any [assert-type]
File "constructors_callable.py", line 142, in <module>: Callable[[Any], Class6Any] [reveal-type]
File "constructors_callable.py", line 143, in <module>: Function <callable> expects 1 arg(s), got 0 [wrong-arg-count]
File "constructors_callable.py", line 161, in <module>: Callable[[Any], Class7] [reveal-type]
File "constructors_callable.py", line 164, in <module>: Class7 [assert-type]
File "constructors_callable.py", line 165, in <module>: Class7 [assert-type]
File "constructors_callable.py", line 182, in <module>: Callable[[Any], Class8[nothing]] [reveal-type]
File "constructors_callable.py", line 183, in <module>: Function <callable> expects 1 arg(s), got 2 [wrong-arg-count]
File "constructors_callable.py", line 183, in <module>: Any [assert-type]
File "constructors_callable.py", line 184, in <module>: Function <callable> expects 1 arg(s), got 2 [wrong-arg-count]
File "constructors_callable.py", line 193, in <module>: Callable[[Any], Class9] [reveal-type]
File "constructors_callable.py", line 194, in <module>: Function <callable> expects 1 arg(s), got 2 [wrong-arg-count]
File "constructors_callable.py", line 194, in <module>: Any [assert-type]
File "constructors_callable.py", line 195, in <module>: Function <callable> expects 1 arg(s), got 2 [wrong-arg-count]
"""
