conformant = "Partial"
notes = """
Does not properly support assert_type.
"""
output = """
File "generics_upper_bound.py", line 24, in Test: Invalid TypeVar: bound cannot contain TypeVars [invalid-typevar]
File "generics_upper_bound.py", line 37, in <module>: list [assert-type]
File "generics_upper_bound.py", line 38, in <module>: set [assert-type]
File "generics_upper_bound.py", line 43, in <module>: Union[list, set] [assert-type]
File "generics_upper_bound.py", line 51, in <module>: Function longer was called with the wrong arguments [wrong-arg-types]
File "generics_upper_bound.py", line 56, in <module>: Invalid TypeVar: constraints and a bound are mutually exclusive [invalid-typevar]
"""
conformance_automated = "Fail"
errors_diff = """
Line 37: Unexpected errors ['File "generics_upper_bound.py", line 37, in <module>: list [assert-type]']
Line 38: Unexpected errors ['File "generics_upper_bound.py", line 38, in <module>: set [assert-type]']
"""
