conformance = "Unsupported"
notes = """
Does not support `typing.Unpack`.
Does not support unpacked tuples within a tuple type form.
"""
output = """
File "tuples_unpacked.py", line 13, in <module>: typing.Unpack not supported yet [not-supported-yet]
File "tuples_unpacked.py", line 13, in <module>: typing.TypeVarTuple not supported yet [not-supported-yet]
File "tuples_unpacked.py", line 16, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 17, in func1: Tuple[Any] [assert-type]
File "tuples_unpacked.py", line 18, in func1: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 19, in func1: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 25, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 26, in func2: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 31, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 31, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 32, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 32, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 37, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 37, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 38, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 39, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 39, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 40, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 40, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 44, in <module>: Function TypeVarTuple.__init__ expects 1 arg(s), got 2 [wrong-arg-count]
File "tuples_unpacked.py", line 47, in <module>: Invalid type annotation '<instance of Tuple[nothing, ...]>'  [invalid-annotation]
File "tuples_unpacked.py", line 48, in func3: Invalid type annotation 'tuple[*tuple[str], *Ts]'  [invalid-annotation]
File "tuples_unpacked.py", line 49, in func3: Invalid type annotation 'tuple[*tuple[str, ...], *Ts]'  [invalid-annotation]
"""
